spring:
  application:
    name: reservation
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reservation?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password:
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create

jwt:
  secret: and0LXRlc3QtYWxqamFiYWVnaS1qd3QtdGVzdC1hbGpqYWJhZWdpLWp3dC10ZXN0LWFsamphYmFlZ2ktand0LXRlc3QtYWxqamFiYWVnaS1qd3QtdGVzdC1hbGpqYWJhZWdpLWp3dC10ZXN0LWFsamphYmFlZ2ktand0LXRlc3QtYWxqamFiYWVnaS1qd3QtdGVzdC1hbGpqYWJhZWdp